databases:
 - name: picnicapp
   databaseName: picnicapp
   user: caroline

services:
 - type: web
   name: picnicapp
   env: python
   buildCommand: "./build.sh"
   startCommand: "gunicorn picnic.wsgi:application"
   envVars:
     - key: DATABASE_URL
       fromDatabase:
         name: picnicapp
         property: connectionString
     - key: SECRET_KEY
       generateValue: true
     - key: WEB_CONCURRENCY
       value: 4
